from __future__ import annotations

from pathlib import Path


class ScaffoldError(RuntimeError):
    """Raised when a starter project cannot be created."""


MOCK_CONFIG = """version: 1

project:
  name: fir-filter-study
  workspace: .dse

parameters:
  DATA_WIDTH:
    values: [8, 12, 16, 24]
  TAPS:
    values: [4, 8, 16, 32]
  PIPELINE_STAGES:
    values: [0, 1, 2, 3]

parameter_constraints:
  - DATA_WIDTH * TAPS <= 512
  - PIPELINE_STAGES <= TAPS

search:
  strategy: grid
  seed: 7
  max_designs: 1000

execution:
  adapter: mock
  jobs: 4
  mock_delay_ms: 5
  mock_metrics:
    lut: round(90 + DATA_WIDTH * TAPS * 0.82 + PIPELINE_STAGES * 24)
    ff: round(40 + DATA_WIDTH * PIPELINE_STAGES * 1.8 + TAPS * 3)
    dsp: ceil(DATA_WIDTH * TAPS / 96)
    fmax_mhz: round(155 + PIPELINE_STAGES * 68 - DATA_WIDTH * 1.7 - TAPS * 0.65, 2)
    latency_cycles: 2 + PIPELINE_STAGES
    throughput_samples_per_cycle: 1
    estimated_power_w: round(0.35 + DATA_WIDTH * TAPS * 0.0009 + PIPELINE_STAGES * 0.02, 4)

metric_constraints:
  - fmax_mhz >= 150
  - lut <= 1000

objectives:
  - metric: fmax_mhz
    goal: maximize
    weight: 0.45
  - metric: lut
    goal: minimize
    weight: 0.30
  - metric: estimated_power_w
    goal: minimize
    weight: 0.15
  - metric: latency_cycles
    goal: minimize
    weight: 0.10
"""

README = """# FIR Filter Design-Space Study

This directory was generated by `fpga-dse init`.

```bash
python -m venv .venv
# Windows: .venv\\Scripts\\activate
# macOS/Linux: source .venv/bin/activate
pip install fpga-dse
fpga-dse validate dse.yml
fpga-dse plan dse.yml
fpga-dse run dse.yml
```

Open `.dse/reports/report.html` after the run. The mock backend is deterministic and does not require FPGA software or hardware. Replace `execution.adapter` with `shell` when your synthesis script can write a `result.json` file.
"""

GITIGNORE = """.dse/
.venv/
__pycache__/
*.py[cod]
"""


def create_scaffold(directory: str | Path, *, force: bool = False) -> tuple[Path, ...]:
    root = Path(directory).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    files = {
        root / "dse.yml": MOCK_CONFIG,
        root / "README.md": README,
        root / ".gitignore": GITIGNORE,
    }
    conflicts = [path for path in files if path.exists()]
    if conflicts and not force:
        joined = ", ".join(str(path) for path in conflicts)
        raise ScaffoldError(f"refusing to overwrite existing files: {joined}; pass --force")
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
    return tuple(files)
